addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.4.13")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.4.13")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.4.13")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.15.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.2.0")
addSbtPlugin("io.chrisdavenport" % "sbt-npm-package" % "0.1.1")